# Generated by Django 4.0 on 2022-04-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_rename_emails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateField(),
        ),
    ]
